---
driver:
  name: vagrant

provisioner:
  name: ansible_push
  ansible_config: test/ansible.cfg
  verbose: v
  diff: true
  chef_bootstrap_url: nil

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04

suites:
  - name: default
    provisioner:
      playbook: test/integration/default/playbook.yml
