---
- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: install gnupg-curl
  apt:
    name: gnupg-curl
  when: ansible_distribution_version is version('18.04', '<')

- name: docker repository key
  apt_key:
    id: "{{ docker_apt_key_sig }}"
    keyserver: "{{ docker_apt_key_url }}"
    state: present

- name: docker repository
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    filename: docker
    update_cache: true
    state: present

- name: install docker
  apt:
    name: "{{ docker_package_name }}\
      {% if (docker_package_version|length > 0) and (docker_package_version != 'latest') %}\
      ={{ docker_package_version }}\
      {% endif %}"
    state: "{{ 'latest' if docker_package_version == 'latest' else 'present' }}"
