---
- name: insall dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - gnupg-curl

- name: add docker repository key
  apt_key:
    id: "{{ docker_apt_key_sig }}"
    keyserver: "{{ docker_apt_key_url }}"
    state: present

- name: add docker repo
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    update_cache: yes
    state: present

- name: install kernel extras
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
  when: docker_install_kernel_extras

- name: install docker package
  apt:
    name: "{{ docker_package_name + '=' + docker_package_version if (docker_package_version and docker_package_version != 'latest') else docker_package_name }}"
    state: "{{ 'latest' if docker_package_version == 'latest' else 'present' }}"

- name: set docker daemon options
  copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0640
  notify:
    - restart docker

- name: install pip
  package:
    name: python-pip
    state: present
  when: docker_install_docker_py

- name: pip install docker-py
  pip:
    name: docker-py
    version: "{{ docker_py_version if (docker_py_version and docker_py_version != 'latest') else omit }}"
    state: "{{ 'latest' if docker_py_version == 'latest' else 'present' }}"
  when: docker_install_docker_py
