---
- include: "install_{{ ansible_os_family | lower }}.yml"

- name: create docker config directory
  file:
    path: /etc/docker
    state: directory

- name: set docker daemon options
  copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0640
  notify:
    - restart docker

- name: manage docker service
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- include: docker_compose.yml
  when: docker_install_compose | bool
